"""the inbox: conversations and the messages in them

Two tables and one rule worth naming here. `conversations.assistant_enabled`
starts `true` and is switched off by the service the moment a person from the
business writes in a thread — it is a switch rather than a log, so there is no
timestamp beside it. And the three `last_message_*` columns are a copy of the
newest message, kept because the list screen is "every thread, newest first,
with a line of preview" and getting that out of SQL is a lateral join on every
read; `ConversationService` is their only writer.


Revision ID: 0020
Revises: 0019
Create Date: 2026-08-26 17:58:06.434069

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0020'
down_revision: str | None = '0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), server_default='whatsapp', nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('assistant_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_author', sa.String(length=16), nullable=True),
    sa.Column('last_message_preview', sa.String(length=160), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel in ('whatsapp')", name=op.f('ck_conversations_channel')),
    sa.CheckConstraint("status in ('new', 'open', 'closed')", name=op.f('ck_conversations_status')),
    sa.CheckConstraint('unread_count >= 0', name=op.f('ck_conversations_unread')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_conversations_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('business_id', 'channel', 'external_id', name='business_id_channel_external_id')
    )
    op.create_index(op.f('ix_conversations_business_id'), 'conversations', ['business_id'], unique=False)
    op.create_index('ix_conversations_business_last', 'conversations', ['business_id', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("author in ('client', 'assistant', 'owner')", name=op.f('ck_messages_author')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'external_id', name='conversation_id_external_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_sent', 'messages', ['conversation_id', 'sent_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_sent', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_business_last', table_name='conversations')
    op.drop_index(op.f('ix_conversations_business_id'), table_name='conversations')
    op.drop_table('conversations')
