/**
 * Cities of Kazakhstan, for the business profile's city picker.
 *
 * Names are the Russian forms, to match the rest of the interface. Recent
 * renames are listed under their current names only — Конаев rather than
 * Капшагай, Алтай rather than Зыряновск — since that's what a client typing an
 * address today will use.
 *
 * Sorted once at module load rather than in the component: the order never
 * changes, and `localeCompare` with a Russian collator is what puts Ё and Щ
 * where a Russian speaker expects them.
 */
export const KAZAKHSTAN_CITIES = [
  'Абай',
  'Аксай',
  'Аксу',
  'Актау',
  'Актобе',
  'Алга',
  'Алматы',
  'Алтай',
  'Аральск',
  'Аркалык',
  'Арыс',
  'Астана',
  'Атбасар',
  'Атырау',
  'Аягоз',
  'Байконыр',
  'Балхаш',
  'Булаево',
  'Державинск',
  'Ерейментау',
  'Есиль',
  'Жанаозен',
  'Жанатас',
  'Жаркент',
  'Жезказган',
  'Жем',
  'Житикара',
  'Зайсан',
  'Казалинск',
  'Кандыагаш',
  'Караганда',
  'Каражал',
  'Каратау',
  'Каркаралинск',
  'Каскелен',
  'Кентау',
  'Кокшетау',
  'Конаев',
  'Косшы',
  'Костанай',
  'Курчатов',
  'Кызылорда',
  'Ленгер',
  'Лисаковск',
  'Макинск',
  'Мамлютка',
  'Павлодар',
  'Петропавловск',
  'Приозерск',
  'Риддер',
  'Рудный',
  'Сарань',
  'Сарканд',
  'Сарыагаш',
  'Сатпаев',
  'Семей',
  'Сергеевка',
  'Степногорск',
  'Степняк',
  'Тайынша',
  'Талгар',
  'Талдыкорган',
  'Тараз',
  'Текели',
  'Темир',
  'Темиртау',
  'Тобыл',
  'Туркестан',
  'Уральск',
  'Усть-Каменогорск',
  'Ушарал',
  'Уштобе',
  'Форт-Шевченко',
  'Хромтау',
  'Шалкар',
  'Шар',
  'Шардара',
  'Шахтинск',
  'Шемонаиха',
  'Шу',
  'Шымкент',
  'Щучинск',
  'Экибастуз',
  'Эмба',
].sort((a, b) => a.localeCompare(b, 'ru'))
